version: '3.8'
services:
  grafana:
    image: simpledotorg/heart360tk-grafana:${HEART360TK_VERSION}
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      ## TODO: move this to image
      - GF_TIME_PICKER_QUICK_RANGES=[{"from":"now-6M","to":"now","display":"Last 6 months"},{"from":"now-1y","to":"now","display":"Last year"},{"from":"now-2y","to":"now","display":"Last 2 years"},{"from":"now-5y","to":"now","display":"Last 5 years"}]
      - GF_DATABASE_URL=postgres://grafana:your_secure_password@postgres:5432/metrics_db
      - GF_SECURITY_ADMIN_PASSWORD=your_secure_password

  postgres:
    image: simpledotorg/heart360tk-postgresql:${HEART360TK_VERSION}
    container_name: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
    ## TODO: change this & move some to image
      - POSTGRES_USER=grafana_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=metrics_db
    volumes:
      - ./.database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
