version: '3.8'
services:
  grafana:
    image: simpledotorg/heart360tk-grafana:${HEART360TK_VERSION}
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      ## TODO: move this to image
      - GF_TIME_PICKER_QUICK_RANGES=[{"from":"now-6M","to":"now","display":"Last 6 months"},{"from":"now-1y","to":"now","display":"Last year"},{"from":"now-2y","to":"now","display":"Last 2 years"},{"from":"now-5y","to":"now","display":"Last 5 years"}]
      - GF_DATABASE_URL=postgres://grafana:your_secure_password@postgres:5432/metrics_db
      - GF_SECURITY_ADMIN_PASSWORD=your_secure_password

  postgres:
    image: simpledotorg/heart360tk-postgresql:${HEART360TK_VERSION}
    container_name: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
    ## TODO: change this & move some to image & take from .env
      - POSTGRES_USER=grafana_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=metrics_db
    volumes:
      - ./.database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s



  file-processor:
    image: simpledotorg/heart360tk-fileprocessor:${HEART360TK_VERSION}
    container_name: file-upload-trigger
   # entrypoint: /bin/sh /scripts/init.sh
    environment:
      - H360TK_DATA_LOAD_SCRIPT=/scripts/ingest_file_puskesmas.py
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=grafana_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=metrics_db
    volumes:
      - ./ingest_file_puskesmas.py:/scripts/ingest_file_puskesmas.py
      - .upload:/data:rw
      


###
# For now, still taken from the base image
###
# TODO: have configuration (like users) dumped out of the container, to avoid losing it
# when reinstalling
  filebrowser:
    image: gtstef/filebrowser:stable-slim
    container_name: filebrowser-quantum
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .upload:/srv:rw
    environment:
      - FILEBROWSER_ADMIN_PASSWORD=admin
      - FILEBROWSER_BASEURL=/

